### PR TITLE
Added high score support.

### PR DESCRIPTION
**Pull request by pickedusername22**
Also changed the score to be unsigned.

### CODE REVIEW

**Comment by trosh** [comment]
High score is a nice touch; don't know if I'm a fan of the defined filename but that's a good start.

Please refrain from using unsigned types unless you have a specific reason to (variables that represent positive values are not a specific reason to use unsigned types).

**Comment by pickedusername22** [comment]
The filename reminds me of some old DOS game from my childhood. It used "his" extension. Now we are not limited to 8.3 file names, so can use something more meaningful.
You got me confused, if the requirement of being only positive is not enough to be unsigned then what is?
I can't count number of times I managed to get negative scores in various games due to overflows...

**Comment by trosh** [comment]
The default filename is not an issue, but then it is not configurable and is always relative to working directory at launch, that seems a bit weird to me.

You don't fix an underflow issue but using unsigned types, that just hides the problem and instead of having the negative value reflecting the problem you now have a meaningless and difficult to detect huge positive value. For example, see “§On unsigned integers” in [Google's C++ style guide](https://google.github.io/styleguide/cppguide.html#Integer_Types).

**Comment by pickedusername22** [comment]
Oh, completely missed the current working directory bit.
Do you think the high score file deserves a place under "~/.config/1010.hiscore"? Do you really think that needs to be configurable?
Regarding the "meaningless huge positive values" - there is no need to "detect" them. That's the whole point of a high score, no problems with huge positive numbers. I agree that using an unsigned number does not fully solve the overflow problem, however it moves it twice as far away. I am not sure what to do if someone manages to overflow 32 bit score. What would be a suitable solution apart from going into arbitrary length precision?

**Comment by trosh** [comment]
I don't have a better high score file scheme that is cross-platform/configurable/KISS off the top of my head, so that's why I said your proposal is just fine for now.

If you want to enforce minimum/maximum values, do an active check within typed bounds before increment or something, that's not what types are for.

My general rule is: if you're trying to keep track of a number, use an int. If it might be outside of [-2**15, 2**15-1], use a long int. If it might be outside of [-2**31, 2**31-1], use a long long int. If you really need modulo arithmetics or to save memory, then start looking at precisely sized types and unsigned ones.

On September 8, 2018 12:17:05 PM GMT+02:00, pickedusername22 <notifications@github.com> wrote:
>Oh, completely missed the current working directory bit.
>Do you think the high score file deserves a place under
>"~/.config/1010.hiscore"? Do you really think that needs to be
>configurable?
>Regarding the "meaningless huge positive values" - there is no need to
>"detect" them. That's the whole point of a high score, no problems with
>huge positive numbers. I agree that using an unsigned number does not
>fully solve the overflow problem, however it moves it twice as far
>away. I am not sure what to do if someone manages to overflow 32 bit
>score. What would be a suitable solution apart from going into
>arbitrary length precision?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/trosh/1010/pull/4#issuecomment-419629619

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pickedusername22** [comment]
You are right, I briefly researched the possibility of getting current executable path to look for the high score file, but it seems to be significantly different under different platforms. BTW, did you try compiling on anything but Linux? Mac? BSDs? Cygwin? I really start regretting that I dived into this feature;o)
For the purposes of this game, using long long int would probably be enough for the foreseeable future  (unless someone decides to  implement a perfectly-playing bot;o) ).
I don't have much experience with C, so forgive me if that's one of those "taboo" things. However, CPUs have a dedicated overflow bit/flag, thus using unsigned values does not "hide" anything. In asm you can perfectly detect overflows with unsigned integers if necessary. So, without losing anything this gives you a free range*2 extension with the extra bit. Pity if C can't have this advantage.

**Comment by trosh** [comment]
I haven't tried under anything else than Linux because it's a small pet project as far as I'm concerned (even though I enjoy your contributions!)

I'm sure you can find a way to detect under/overflows after the fact in C, but that's not better nor easier than checking whether the operation will under/overflow before applying it. This is still unrelated to using unsigned types, which make comparisons, assignments, checking for under/overflow all more bothersome for some really hard to justify benefit.

On September 8, 2018 12:59:12 PM GMT+02:00, pickedusername22 <notifications@github.com> wrote:
>You are right, I briefly researched the possibility of getting current
>executable path to look for the high score file, but it seems to be
>significantly different under different platforms. BTW, did you try
>compiling on anything but Linux? Mac? BSDs? Cygwin? I really start
>regretting that I dived into this feature;o)
>For the purposes of this game, using long long int would probably be
>enough for the foreseeable future  (unless someone decides to 
>implement a perfectly-playing bot;o) ).
>I don't have much experience with C, so forgive me if that's one of
>those "taboo" things. However, CPUs have a dedicated overflow bit/flag,
>thus using unsigned values does not "hide" anything. In asm you can
>perfectly detect overflows with unsigned integers if necessary. So,
>without losing anything this gives you a free range*2 extension with
>the extra bit. Pity if C can't have this advantage.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/trosh/1010/pull/4#issuecomment-419633145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trosh** [comment]
Also, don't worry it's not a taboo, and EVERYBODY does it all the time. I have to deal with the ensuing bothers every day so I'd just like to avoid that in my code 😛

**Comment by pickedusername22** [comment]
Lets forget about the path then for now.
I remember in one game I even managed to overflow 64-bit scoring (granted that had 2x multipliers ;o) ). Does that even make sense to limit the high score to a predefined value? Suppose we successfully detect a potential overflow, what then? I'd say in this case the problem is not the type, but what to actually do if an overflow is detected (regardless whether it happens before or after the fact). I simply don't see a generic enough solution. Should the game simply end?

**Comment by trosh** [comment]
Use GMP then haha

On September 8, 2018 1:20:48 PM GMT+02:00, pickedusername22 <notifications@github.com> wrote:
>Lets forget about the path then for now.
>I remember in one game I even managed to overflow 64-bit scoring
>(granted that had 2x multipliers ;o) ). Does that even make sense to
>limit the high score to a predefined value? Suppose we successfully
>detect a potential overflow, what then? I'd say in this case the
>problem is not the type, but what to actually do if an overflow is
>detected (regardless whether it happens before or after the fact). I
>simply don't see a generic enough solution. Should the game simply end?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/trosh/1010/pull/4#issuecomment-419634540

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pickedusername22** [comment]
Then I will start worrying about running out of RAM and disk space;o)
Perhaps the best thing we can do is to use long long int and hope that no one plays that good.

**Comment by trosh** [comment]
Yes, realistically just use a long long and saturate at max_long_long_int

On September 8, 2018 1:39:55 PM GMT+02:00, pickedusername22 <notifications@github.com> wrote:
>Then I will start worrying about running out of RAM and disk space;o)
>Perhaps the best thing we can do is to use long long int and hope that
>no one plays that good.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/trosh/1010/pull/4#issuecomment-419635649

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trosh** [comment]
Nice, thanks !

**Pull request merged**
