### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pickedusername11**
Fixed the known bugs and added scoring.

### CODE REVIEW

**Comment by trosh** [comment]
I'm absolutely amazed you did this, whoever you are. Will try when possible.

The commit's message doesn't seem to be related to the content? The pull request's description seems better.

**Comment by trosh** [comment]
I pulled changes, rewrote some of the history.

Played a bit, it's OK but:

* My level has really gone down

* Selecting a default block among the selection of three seems bad in retrospect

* This really works better with a touch screen and a visible grid

Thanks for the fixes and scoring :smiley:

I'm still not sure why raising the loop bounds from 5 to 10 fixes the loss detection, care to explain ?

**Comment by trosh** [comment]
Oh actually I just understood the bounds how goofy of me

I think at some point I'd figured it out and instead of brutishly looping like this I wanted to loop only as needed by the blocks. That's more complicated though and brings no real benefit so your solution is good.

**Comment by pickedusername11** [comment]
Hi,
Sorry for the pull request title. Somehow missed that. It's the second time I'm using github.
I've created another pull request regarding the block selection.
There is no block selected by default now.
I also added an ability to select previous/next block with , and . (or < and >) - please have a look. Makes it more comfortable to play with one hand.
I know it plays better on a touch screen, but sometimes I only have a terminal in front of me.
It may be possible to implement a grid using unicode line-drawing characters.
Not sure if that'll look OK though. Will experiment a bit.

Regards.

**Comment by pickedusername11** [comment]
Check my fork for the grid version.
Doesn't look too good, but works.

**Comment by trosh** [comment]
This is the first time someone contributed on a project by me I think, this is cool.

I'll be slightly pedantic but instead of rewriting your commits I'll give you feedback here.

* The grid looks good I think, takes a minute to get used to but that's fine.
  I'm going to try to colour borders between blocks and see what that does.

* Switching with `<` / `>` needs two changes:
  if no block is selected, `>` should choose block 1, `<` should choose block 3;
  currently both directions do the same thing, but `<` should do `--b`.
  Also I'm not personally fond of playing like that, not sure how you do it with one hand,
  but who am I to judge.

Also, you don't need to fork again when histories diverge.
If you agreed to discard your side of history you could just have done something like :
```sh
$ git remote add trosh https://github.com/trosh/1010
$ git fetch trosh master
$ git reset --force trosh/master
```

**Comment by trosh** [comment]
OK I posted a big comment here, realized I wanted it in the other pull request, screwed up and lost the comment. You may have received a copy by mail, otherwise tell me and I'll try to rewrite.

**Comment by pickedusername11** [comment]
Sorry, didn't receive anything.

**Pull request closed without merging**
